#!/usr/bin/env bash

if [ "$1" = "logs" ]; then
    pod="$(echo `oc get pods | grep jenkins | awk '{ print $1 }' | sed 's/,/\n/g'`)"
    oc logs -f $pod

elif [ "$1" = "load" ]; then
    pluginPath=`realpath $2`
    if [ ! -f $pluginPath ]; then
        echo "File not found!"
    else
        jenkinsNamespace="$3" #`oc get projects | grep jenkins | awk '{print $1}'`
        jenkinsService="jenkins-$jenkinsNamespace"
        jenkinsRoute=$(echo `oc get route -n $jenkinsNamespace | grep $jenkinsService | awk '{print $2}'`)
        python3 /home/vibhavbobade/Documents/scripts/jenkinsInstallPlugin/automatePluginInstall.py $jenkinsRoute $pluginPath
    fi
fi 
