#!/usr/bin/env bash

#######
#      
#       jip logs <namespace>
#       jip open <namespace> 
#       jip load <namespace> <plugin path>
#
#######



jipDir="$(dirname "$(realpath "$0")")"
jenkinsNamespace="$2"
jenkinsRoute=""
pluginPath="./"

function setRoute {
    #set route
    jenkinsRoute=$(echo `oc get route -n $jenkinsNamespace | grep jenkins-$jenkinsNamespace | awk '{print $2}'`)
    # Print info
    echo "----------------------------"
    echo Namespace : $jenkinsNamespace
    echo Route : $jenkinsRoute
    echo Plugin Path : $pluginPath
    echo "----------------------------"
}

if [ "$1" = "logs" ]; then
    pod="$(echo `oc get pods | grep jenkins | awk '{ print $1 }' | sed 's/,/\n/g'`)"
    oc logs -f $pod

elif [ "$1" = "open" ]; then
    setRoute
    python3 $jipDir/main.py $jenkinsRoute

elif [ "$1" = "load" ]; then
    pluginPath=`realpath $3`
    if [ ! -f $pluginPath ]; then
        echo "File not found!"
    else
        setRoute
        python3 $jipDir/main.py $jenkinsRoute $pluginPath
    fi

fi 
