#!/usr/bin/env bash

FILTER="e2e"

# Stop Kubectl Proxy
process=`netstat -tulp | grep kubectl | awk '{print $7}'`
pid=(${process//\// })
kill -9 $pid
# Start Kubectl proxy
kubectl proxy &

if [ "$1" = "-f" ];
then
    if [ ! -z "$2" ];
    then
        FILTER=$2
    fi
fi

for NAMESPACE in `oc get projects | grep $FILTER | awk '{print $1}'` 
do 
    if [ "$1" = "-f" ]
    then
        (
        kubectl get namespace $NAMESPACE -o json |jq '.spec = {"finalizers":[]}' >/tmp/temp.json
        curl -k -H "Content-Type: application/json" -X PUT --data-binary @/tmp/temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
        )
    else
        oc delete project $NAMESPACE;  
    fi
done 
